import "./globals.css";
import FeatherIcon from "feather-icons-react";


export const metadata = {
  title: "Minel Salihagić",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-Navy w-full flex flex-col">
    <nav className="bg-Navy h-24 z-20 text-Green px-6 md:px-12 py-4 flex items-center justify-between">
      <p className="text-3xl text-Green">M</p>
      <div className="flex gap-4 items-center font-sf-mono text-Green">
          <p>01</p>
          <p>02</p>
          <p>03</p>
      </div>
    </nav>
    <div className="w-full flex h-[200vh]">
        <div className="z-10 hidden md:flex fixed top-0 left-0 w-1/12 flex-col items-center justify-end bg-Navy h-full">
            <div className="flex flex-col items-center gap-8">
                <FeatherIcon
                icon="github"
                className="text-Slate w-6 h-6 stroke-current transition-transform duration-300 ease-in-out transform hover:translate-y-[-5px] hover:cursor-pointer hover:text-Green"
                strokeWidth="2"
              />
                <FeatherIcon
                icon="instagram"
                className="text-Slate w-6 h-6 stroke-current transition-transform duration-300 ease-in-out transform hover:translate-y-[-5px] hover:cursor-pointer hover:text-Green"
                strokeWidth="2"
              />
                <FeatherIcon
                icon="linkedin"
                className="text-Slate w-6 h-6 stroke-current transition-transform duration-300 ease-in-out transform hover:translate-y-[-5px] hover:cursor-pointer hover:text-Green"
                strokeWidth="2"
              />
                <FeatherIcon
                icon="twitter"
                className="text-Slate w-6 h-6 stroke-current transition-transform duration-300 ease-in-out transform hover:translate-y-[-5px] hover:cursor-pointer hover:text-Green"
                strokeWidth="2"
              />
                <FeatherIcon
                icon="facebook"
                className="text-Slate w-6 h-6 stroke-current transition-transform duration-300 ease-in-out transform hover:translate-y-[-5px] hover:cursor-pointer hover:text-Green"
                strokeWidth="2"
              />
              

                
                  <div className="w-[1px] h-24 bg-Slate">

                  </div>
            </div>
        </div>
        
        <div className="w-full md:w-10/12 md:ml-[8.33%]"></div>
        
        <div className="hidden md:flex fixed top-0 right-0 w-1/12 flex-col items-center justify-end bg-Navy h-full">
         <div className="flex flex-col items-center gap-8">
              
        <p className="z-10 text-Slate text-md font-sf-mono rotate-90 mb-24 transition-transform duration-300 ease-in-out transform hover:translate-y-[-5px] hover:cursor-pointer hover:text-Green">minelsalihagic@gmail.com</p>

                
                  <div className="w-[1px] h-24 bg-Slate">

                  </div>
            </div></div>
    </div>
</body>



    </html>
  );
}
